language: java
jdk: openjdk7
before_install:
  - chmod +x prepare-build.sh
  - ./prepare-build.sh
script: mvn package
after_success:
  - cd /tmp
  - git clone https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} innerbuilder
  - cd innerbuilder
  - cp $TRAVIS_BUILD_DIR/innerbuilder.jar .
  - git config --global user.name $GIT_AUTHOR_NAME
  - git config --global user.email $GIT_AUTHOR_EMAIL
  - git add innerbuilder.jar
  - git commit -m "[ci skip] Committed by Travis-CI"
  - git push https://${GH_OAUTH_TOKEN}@github.com/${GH_USER_NAME}/${GH_PROJECT_NAME} 2>&1
env:
  global:
  - GH_USER_NAME: analytically
  - GH_PROJECT_NAME: innerbuilder
  - GIT_AUTHOR_NAME: TravisCI
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - CI_HOME=`pwd`/$TRAVIS_REPO_SLUG
  - secure: j0qZap7xa4NlqMrMcspU2hTrltA2x1o7krsQzr/beD1BiiZWccXeJNvCc4uxhjKlS230PyVoT2WoNxLmWuv5iGOly51YcReMfprp9M8b5wP2Y2yiZJu5jKjh6RWbutXs47sSc0mn2CZM6D3qjaNzIpXzxpyHTyQWMVokvshITlw=
